name: C/C++ CI

on:
  push:
    branches: [ master, improve-computation-api ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make install
      run: make install
    - name: make test
      run: ./build/bin/iegenlib_t
