name: build/test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    # defaults:
    #   run:
    #     shell: bash
    steps:
    - name: Complete flex installation
      run: sudo apt-get install libfl-dev
    - uses: actions/checkout@v2
    - name: set TERM
      run: echo "TERM=xterm-256color" >> $GITHUB_ENV
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make install
      run: make install
    - name: set IEGEN_HOME
      run: echo "IEGEN_HOME=$GITHUB_WORKSPACE/iegen" >> $GITHUB_ENV
    - name: run tests
      run: ./build/bin/iegenlib_t
    - name: build tutorial examples
      run: make tutorial
